### ISSUE TITLE
undefined symbol: VR_InitInternal2

### ISSUE THREAD

**Issue by DASPRiD** [SieR-VR/openvr.js#2]
NodeJS version: 16.13.1 / Linux
openvr.js version: 0.3.1

When trying to run the following code:

```typescript
ivrSystem = vr.VR_Init(vr.EVRApplicationType.VRApplication_Overlay);
```

I receive the following error:

```
node: symbol lookup error: […]/node_modules/openvr.js/build/Release/openvr.node: undefined symbol: VR_InitInternal2
```

**Comment by SieR-VR** [comment]
I've implemented these stuffs for windows, so It will not works on linux. I'll add some linux features in gyp.

**Comment by SieR-VR** [comment]
I changed files but I couldn't test it. Can you run it and notify me?

**Comment by DASPRiD** [comment]
This looks slightly better:

```
Error: libopenvr_api.so: cannot open shared object file: No such file or directory
```

**Comment by SieR-VR** [comment]
Umm.. was openvr.node file generated?

**Comment by DASPRiD** [comment]
Yeah:

![image](https://user-images.githubusercontent.com/233300/144857689-bf44d955-6935-48f6-8d1c-d11c2e37c92b.png)

**Comment by SieR-VR** [comment]
It will work maybe. I added copying dynamic library files.

**Comment by DASPRiD** [comment]
Still no dice. I googled for that, and other gyp users seem to struggle with the same issue, although with no solution attached:

https://github.com/nodejs/node-gyp/issues/2258

By the way, I assume you could test this on Windows with the Linux Subsystem for Windows? Just an idea, but I have no issue testing for you :)

**Comment by SieR-VR** [comment]
![image](https://user-images.githubusercontent.com/51986318/144863211-00fdb76c-a240-4f46-86de-01b3ecf5a51c.png)
I tested it on wsl. When I ejected dynamic library file to project root, There's some progress.

**Comment by DASPRiD** [comment]
That one should usually be supplied by the host system, so you could potentially ignore that.

**Comment by SieR-VR** [comment]
Well, I don't know which linux distribution are you using, you'll need add openvr dynamic library to global.

**Comment by DASPRiD** [comment]
I guess that's fair enough :)

By the way, this makes we wonder, where does Windows take the `libopenvr_api.dll` from?

**Comment by SieR-VR** [comment]
npm package contains openvr_api.dll. I guess this difference came from difference of method of searching library file.

**Comment by DASPRiD** [comment]
I'll do some more investigation to figure out how to properly link it. If I can get it working directly, I'll open a PR.

**Comment by SieR-VR** [comment]
Thanks!
