### ISSUE TITLE
npm install of latest version fails

### ISSUE THREAD

**Issue by DASPRiD** [SieR-VR/openvr.js#7]
When trying to install the latest (both 0.3.7 and 0.3.8) version, npm throws a bunch of compile errors. This might be related to my latest PR, although I'm not sure.

These are the last few lines:

```
npm ERR! In file included from ../../nan/nan_new.h:189,
npm ERR!                  from ../../nan/nan.h:292,
npm ERR!                  from ../src/ivrapplications.h:4,
npm ERR!                  from ../src/ivrapplications.cpp:1:
npm ERR! ../../nan/nan_implementation_12_inl.h:78:35: note:   initializing argument 1 of ‘static Nan::imp::FactoryBase<v8::External>::return_t Nan::imp::Factory<v8::External>::New(void*)’
npm ERR!    78 | Factory<v8::External>::New(void * value) {
```

**Comment by SieR-VR** [comment]
Oh.. I tested it on windows, I'll fix it for linux until tomorrow.

**Comment by SieR-VR** [comment]
Fixed!

**Comment by DASPRiD** [comment]
Perfect, thanks! Maybe we should set up a github action to run the build on every PR and merge to main (or master, I think you still call it) :)
